// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyK3p4kQZAsedmtZ3JNpvfjazCHUjheMQ',
    appId: '1:584953330392:web:6a8867dea6dfda172835ad',
    messagingSenderId: '584953330392',
    projectId: 'fruit-app-5626f',
    authDomain: 'fruit-app-5626f.firebaseapp.com',
    storageBucket: 'fruit-app-5626f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtHwV7ImP_tjxNGy5lJ0FtaivR7AX3SOo',
    appId: '1:584953330392:android:8a19616d62d779882835ad',
    messagingSenderId: '584953330392',
    projectId: 'fruit-app-5626f',
    storageBucket: 'fruit-app-5626f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRb3EO1wHsZn77gX9pflVaxrfRySnjDnQ',
    appId: '1:584953330392:ios:45f942fde80d1be42835ad',
    messagingSenderId: '584953330392',
    projectId: 'fruit-app-5626f',
    storageBucket: 'fruit-app-5626f.appspot.com',
    iosClientId: '584953330392-ab30q5iosnidv88ad44ao04ovsflteq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitApp',
  );
}
